name: Deploy Applications

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          ssh -i private_key -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /root/home/Building-u-feedback
            git pull origin main
            npm install
            pm2 stop all || true
            pm2 start index.js --name building-u-feedback-api --watch
            pm2 save
            pm2 startup -u ${{ secrets.SSH_USER }} --hp /home/${{ secrets.SSH_USER }}
          EOF
          rm private_key

  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    needs: deploy-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: cd views && npm install

      - name: Build frontend
        run: cd views && npm run build

      - name: Configure Git
        run: |
          git config --global user.name 'buildingu'
          git config --global user.email 'coding@building-U.com'

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd views
          git config --global user.name 'buildingu'
          git config --global user.email 'coding@building-U.com'
          npm run deploy
